# .github/workflows/agendador.yml

name: Executar Script Diariamente

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ----- PASSO ADICIONADO E CORRIGIDO -----
      # Este passo agora será executado. Ele lê o arquivo requirements.txt
      # e instala todas as bibliotecas listadas nele.
      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Corrigi o nome do script para 'main.py' de acordo com seu log.
      - name: Executar o script
        run: python main.py
