# .github/workflows/agendador.yml

name: Executar Script Diariamente

on:
  schedule:
    - cron: '32 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Executar o script
        # ----- ESTE BLOCO É A SOLUÇÃO -----
        # Ele pega cada Secret do cofre do GitHub e o expõe como 
        # uma variável de ambiente para o seu script Python.
        env:
          WHATSAPP_ACCESS_TOKEN: ${{ secrets.WHATSAPP_ACCESS_TOKEN }}
          WHATSAPP_PHONE_NUMBER_ID: ${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}
          META_ADS_ACCESS_TOKEN: ${{ secrets.META_ADS_ACCESS_TOKEN }}
          META_AD_ACCOUNT_ID_BELLA_SERRA: ${{ secrets.META_AD_ACCOUNT_ID_BELLA_SERRA }}
          META_AD_ACCOUNT_ID_VISTA_BELLA: ${{ secrets.META_AD_ACCOUNT_ID_VISTA_BELLA }}
          BOTCONVERSA_API_TOKEN: ${{ secrets.BOTCONVERSA_API_TOKEN }}
          RDSTATION_CRM_TOKEN: ${{ secrets.RDSTATION_CRM_TOKEN }}
          CONTATOS_GRUPO_1: ${{ secrets.CONTATOS_GRUPO_1 }}
          CONTATOS_GRUPO_2: ${{ secrets.CONTATOS_GRUPO_2 }}
        run: python main.py
